#
# syntax: https://docs.docker.com/compose/yml/
#

version: "3"

services:

    user-api:
        #restart: always
        build: user-api/
        image: user-api:0.1.0
        depends_on:
            - postgres
        networks:
            - api-net
        ports:
            - 5000:5000
        env_file: env/stag.env
        volumes:
            - ./user-api/:/build/
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    nginx:
        image: nginx:1.11.6
        depends_on:
            - user-api
        networks:
            - api-net
        ports:
            - "0.0.0.0:80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
        command: /bin/bash -c "nginx -g 'daemon off;'"
        hostname: nginx
        #restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    postgres:
      image: postgres:9.4
      hostname: postgres
      ports:
        - 5432:5432
      # restart: always
      env_file: env/stag.env
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      networks:
        - api-net
      logging:
        driver: "json-file"
        options:
          max-size: "100M"
          max-file: "3"

# volumes:
#     postgres-data:

networks:
  api-net:


